import criteria.FindFlightDetailsByFlightNameCriteria;
import response.FindFlightDetailsByFlightNameResponse;

public interface FindFlightDetailsByFlightNameManager {
    FindFlightDetailsByFlightNameResponse findFlightDetailsByFlightNameResponse(FindFlightDetailsByFlightNameCriteria criteria);
}
